module.exports.codes = {
  MISSING_USERNAME: 'MISSING_USERNAME',
  MISSING_PASSWORD: 'MISSING_PASSWORD',
  UNKNOWN_USERNAME: 'UNKNOWN_USERNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MISSING_EMAIL: 'MISSING_EMAIL',
  UNKNOWN_EMAIL: 'UNKNOWN_EMAIL'
}

module.exports.statuses = {
  MISSING_USERNAME: 400,
  MISSING_PASSWORD: 400,
  UNKNOWN_USERNAME: 400,
  INVALID_PASSWORD: 400,
  MISSING_EMAIL: 400,
  UNKNOWN_EMAIL: 400
}